baseURL = "https://termux.holehan.org"
languageCode = "en-us"
title = "Termux Extra Packages"
theme = "termux"
publishDir = "docs"

enableRobotsTXT = true

pygmentsCodeFences = true
pygmentsStyle = "paraiso-dark"

disableKinds = ["taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML"]
